services:
  # Backend Web Service (Único servicio activo que consumirá las 750 horas gratis)
  - type: web
    name: erp-api
    plan: free
    runtime: python
    rootDir: backend
    buildCommand: git config --global --add safe.directory /opt/render/project/src && git describe --tags --always > version.txt && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: MONGO_DB_NAME
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "1440"
      - key: ALLOWED_ORIGINS
        sync: false
